version: "3"

services:
    user-service:
        image: webdevops/php:8.1
        platform: linux/x86_64
        networks:
            - anser_project_network
        ports:
            - 8080:8080
        working_dir: /app
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_MEMORY_LIMIT=2048M
            - PHP_MAX_EXECUTION_TIME=300
            - PHP_POST_MAX_SIZE=2048M
            - PHP_UPLOAD_MAX_FILESIZE=2048M
        volumes:
            - './app:/app'
        command: >
            bash -c "chmod 776 ./start_service.sh && ./start_service.sh"
    user_DB:
        image: postgres:11.12
        networks:
            - anser_project_network
        environment:
            POSTGRES_DB: user
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - ./user-db-data:/var/lib/postgresql/data/
        ports:
            - "8340:5432"
        command:
            [
                "postgres",
                "-c",
                "logging_collector=on",
                "-c",
                "log_destination=stderr",
                "-c",
                "max_connections=10000"
            ]
    # user_test_DB:
    #     image: postgres:11.12
    #     networks:
    #         - anser_project_network
    #     environment:
    #         POSTGRES_DB: user
    #         POSTGRES_USER: root
    #         POSTGRES_PASSWORD: root
    #     volumes:
    #         - ./user-test-db-data:/var/lib/postgresql/data/
    #     ports:
    #         - "8341:5432"
    #     command:
    #         [
    #             "postgres",
    #             "-c",
    #             "logging_collector=on",
    #             "-c",
    #             "log_destination=stderr",
    #             "-c",
    #             "max_connections=10000"
    #         ]
networks:
    anser_project_network:
        external: true
